language: node_js
node_js:
  - "10.16.3"

script:
  - cd contract && npm install && npm run lint && cd ../web-app/server && npm install && npm run lint && cd ../client && npm install && npm run lint

